# Generated by Django 3.1.5 on 2021-04-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfile',
            old_name='date_add_file',
            new_name='date_send',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='date_send_file',
        ),
    ]
