# Generated by Django 3.1.5 on 2021-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210423_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='result_treatment_data',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
