# Generated by Django 3.1.5 on 2021-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('company', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
